_target_: src.models.epn_mocap_model.EPNMocapLitModel

mlps: [[32,32], [32,32], [32,32], [32, 32]]
out_mlps: [128, 128]
strides: [2, 2, 2, 1]
initial_radius_ratio : 0.2
sampling_ratio : 0.8
sampling_density : 0.5
kernel_density : 1
kernel_multiplier : 2
sigma_ratio: 0.5
lr : 0.005
lr_decay : 0.9995
